const vscode = require('vscode');
const path = require('path');
const fs = require('fs');
const { execFile } = require('child_process');

let outputChannel;
let statusBar;
let syncInterval;

// Allowed git remote owners. Read from the `dotfiles-check.allowedOwners`
// VS Code setting at use-time so users can add work orgs without rebuilding.
function getAllowedOwners() {
  const cfg = vscode.workspace.getConfiguration('dotfiles-check');
  const list = cfg.get('allowedOwners');
  return Array.isArray(list) && list.length ? list : ['nic2045'];
}

function log(msg) {
  const timestamp = new Date().toLocaleTimeString();
  outputChannel.appendLine(`[${timestamp}] ${msg}`);
}

function git(args, cwd) {
  return new Promise((resolve, reject) => {
    execFile('git', args, { cwd }, (err, stdout, stderr) => {
      if (err) reject(new Error(stderr || err.message));
      else resolve(stdout.trim());
    });
  });
}

async function getDotfilesPath() {
  const workspaceFolder = vscode.workspace.workspaceFolders?.[0];
  if (!workspaceFolder) return null;
  const projectDir = workspaceFolder.uri.fsPath;
  const parentDir = path.dirname(projectDir);
  return path.join(parentDir, 'dotfiles');
}

// Returns { isRepo, isRoot, hasCommits, owner, remoteUrl } for the given directory.
async function inspectGitRepo(projectDir) {
  let toplevel;
  try {
    toplevel = await git(['rev-parse', '--show-toplevel'], projectDir);
  } catch {
    return { isRepo: false };
  }

  const isRoot = path.resolve(toplevel) === path.resolve(projectDir);

  // HEAD only resolves once there is at least one commit. A bare `git init`
  // (no commits yet) should not trigger any dotfiles automation — we don't
  // want to seed entries in the dotfiles repo for repos the user hasn't
  // actually started using.
  let hasCommits = false;
  try {
    await git(['rev-parse', '--verify', 'HEAD'], projectDir);
    hasCommits = true;
  } catch {
    // empty repo
  }

  let remoteUrl = '';
  try {
    remoteUrl = await git(['config', '--get', 'remote.origin.url'], projectDir);
  } catch {
    // no remote configured
  }

  const owner = parseGitOwner(remoteUrl);
  return { isRepo: true, isRoot, hasCommits, owner, remoteUrl };
}

// Extract the owner/org from common git remote formats:
//   https://github.com/<owner>/<repo>(.git)
//   git@github.com:<owner>/<repo>(.git)
//   ssh://git@github.com/<owner>/<repo>(.git)
function parseGitOwner(url) {
  if (!url) return null;
  const patterns = [
    /^https?:\/\/[^/]+\/([^/]+)\/[^/]+?(?:\.git)?\/?$/i,
    /^git@[^:]+:([^/]+)\/[^/]+?(?:\.git)?\/?$/i,
    /^ssh:\/\/[^/]+\/([^/]+)\/[^/]+?(?:\.git)?\/?$/i,
  ];
  for (const re of patterns) {
    const m = url.match(re);
    if (m) return m[1];
  }
  return null;
}

function checkClaudeMd(projectDir, dotfilesPath) {
  const claudeMdPath = path.join(projectDir, 'CLAUDE.md');
  const projectName = path.basename(projectDir);
  const expectedTarget = path.join(dotfilesPath, 'claude', 'projects', `${projectName}.md`);

  let stat;
  try {
    stat = fs.lstatSync(claudeMdPath);
  } catch (e) {
    return { ok: false, issue: 'CLAUDE.md missing', claudeMdPath, expectedTarget };
  }

  if (!stat.isSymbolicLink()) {
    return { ok: false, issue: 'CLAUDE.md exists but is not a symlink', claudeMdPath, expectedTarget };
  }

  if (!fs.existsSync(claudeMdPath)) {
    return { ok: false, issue: 'CLAUDE.md is a broken symlink', claudeMdPath, expectedTarget };
  }

  let resolvedTarget;
  try {
    resolvedTarget = fs.realpathSync(claudeMdPath);
  } catch (e) {
    return { ok: false, issue: 'CLAUDE.md is a broken symlink', claudeMdPath, expectedTarget };
  }

  if (resolvedTarget !== expectedTarget) {
    return { ok: false, issue: 'CLAUDE.md symlink points to wrong target', claudeMdPath, expectedTarget };
  }

  return { ok: true };
}

// Make sure the project repo never leaks the CLAUDE.md symlink to clones:
// - add `CLAUDE.md` to .gitignore (creating the file if needed)
// - if it was previously committed, `git rm --cached` it so it stops being
//   tracked from the next commit onward.
// Both operations are local-only; nothing gets committed or pushed in the
// project repo automatically.
async function protectProjectRepo(projectDir) {
  const gitignorePath = path.join(projectDir, '.gitignore');
  const entry = 'CLAUDE.md';

  try {
    let lines = [];
    let existing = '';
    if (fs.existsSync(gitignorePath)) {
      existing = fs.readFileSync(gitignorePath, 'utf8');
      lines = existing.split(/\r?\n/);
    }
    const alreadyIgnored = lines.some(l => l.trim() === entry || l.trim() === `/${entry}`);
    if (!alreadyIgnored) {
      const needsLeadingNewline = existing.length > 0 && !existing.endsWith('\n');
      fs.appendFileSync(
        gitignorePath,
        `${needsLeadingNewline ? '\n' : ''}# Auto-generated by vscode-dotfiles-check — points into local dotfiles, not portable\nCLAUDE.md\n`
      );
      log('Added CLAUDE.md to project .gitignore');
    }
  } catch (err) {
    log(`Could not update .gitignore: ${err.message}`);
  }

  // Untrack CLAUDE.md if it was committed earlier. `ls-files --error-unmatch`
  // exits non-zero when the file is not tracked, which is the common case.
  try {
    await git(['ls-files', '--error-unmatch', '--', 'CLAUDE.md'], projectDir);
    // Tracked — untrack it so the symlink stops shipping with the repo.
    try {
      await git(['rm', '--cached', '--', 'CLAUDE.md'], projectDir);
      log('Untracked previously-committed CLAUDE.md (commit .gitignore + this change in your next commit)');
      vscode.window.showInformationMessage(
        'CLAUDE.md was tracked by git and has been untracked. Commit the .gitignore change so clones stay clean.'
      );
    } catch (err) {
      log(`Failed to untrack CLAUDE.md: ${err.message}`);
    }
  } catch {
    // not tracked — nothing to do
  }
}

// Commit + push a newly-added project file in the dotfiles repo, so other
// machines pick it up on next sync. Pulls --rebase first to avoid push
// rejections when another machine added projects in the meantime.
async function pushProjectToDotfiles(dotfilesPath, projectName, projectFile) {
  const relPath = path.relative(dotfilesPath, projectFile);
  try {
    log(`Syncing new project '${projectName}' to dotfiles remote...`);
    updateStatusBar('Pushing to dotfiles...', 'syncing');

    // Stage just the new project file; refuse to drag along unrelated dirty state.
    await git(['add', '--', relPath], dotfilesPath);

    const staged = await git(['diff', '--cached', '--name-only'], dotfilesPath);
    if (!staged) {
      log('Nothing staged — project file already tracked, skipping commit');
      return;
    }

    await git(['commit', '-m', `add project: ${projectName}`, '--', relPath], dotfilesPath);

    try {
      await git(['pull', '--rebase', 'origin', 'main'], dotfilesPath);
    } catch (err) {
      log(`Rebase failed (${err.message}) — aborting push to avoid bad state`);
      try { await git(['rebase', '--abort'], dotfilesPath); } catch {}
      vscode.window.showWarningMessage(
        `Dotfiles: could not rebase before push for '${projectName}'. Commit is local; push manually after resolving.`
      );
      return;
    }

    // Push, with one rebase-and-retry if another machine raced us between
    // pull and push (non-fast-forward). Logs each step loudly so the race is
    // visible in the output channel instead of silently swallowed.
    try {
      await git(['push', 'origin', 'main'], dotfilesPath);
    } catch (pushErr) {
      log(`Push rejected — possible race with another machine: ${pushErr.message}`);
      log('Retrying once: pull --rebase + push');
      try {
        await git(['pull', '--rebase', 'origin', 'main'], dotfilesPath);
        await git(['push', 'origin', 'main'], dotfilesPath);
        log('Retry push succeeded');
      } catch (retryErr) {
        log(`Retry push failed: ${retryErr.message}`);
        try { await git(['rebase', '--abort'], dotfilesPath); } catch {}
        throw new Error(`push rejected twice (race or conflict): ${retryErr.message}`);
      }
    }
    log(`Pushed 'add project: ${projectName}' to dotfiles`);
    updateStatusBar('Dotfiles pushed', 'synced');
  } catch (err) {
    log(`Push to dotfiles failed: ${err.message}`);
    vscode.window.showWarningMessage(
      `Dotfiles: auto-push for '${projectName}' failed — ${err.message}. The local symlink is set; push the dotfiles repo manually.`
    );
  }
}

async function syncDotfiles() {
  const dotfilesPath = await getDotfilesPath();
  if (!dotfilesPath || !fs.existsSync(dotfilesPath)) {
    log('Dotfiles not found');
    updateStatusBar('Dotfiles not found', 'notFound');
    return;
  }

  try {
    updateStatusBar('Syncing...', 'syncing');
    log('Starting sync...');

    // Stash local changes if any
    const status = await git(['status', '--porcelain'], dotfilesPath);
    if (status) {
      log('Stashing local changes...');
      await git(['stash'], dotfilesPath);
    }

    // Fetch and check for updates
    await git(['fetch', 'origin', 'main'], dotfilesPath);
    const diff = await git(['diff', 'HEAD', 'origin/main', '--name-only'], dotfilesPath);

    if (diff) {
      log('Updates available, pulling...');
      await git(['pull', 'origin', 'main'], dotfilesPath);
      updateStatusBar('Synced', 'synced');
      log('Dotfiles synced');
      vscode.window.showInformationMessage('Dotfiles synced');
    } else {
      log('Already up to date');
      updateStatusBar('Up to date', 'synced');
    }
  } catch (err) {
    log(`Sync failed: ${err.message}`);
    updateStatusBar('Sync failed', 'error');
    vscode.window.showErrorMessage(`Dotfiles sync failed: ${err.message}`);
  }
}

function updateStatusBar(text, state) {
  const icons = {
    synced:   '$(pass)',
    error:    '$(error)',
    syncing:  '$(sync~spin)',
    notFound: '$(circle-slash)',
    skipped:  '$(circle-slash)',
  };
  statusBar.text = `${icons[state] || '$(circle-slash)'} Dotfiles`;
  statusBar.tooltip = `Dotfiles: ${text}`;

  if (state === 'error') {
    statusBar.backgroundColor = new vscode.ThemeColor('statusBarItem.errorBackground');
    statusBar.color = new vscode.ThemeColor('statusBarItem.errorForeground');
  } else if (state === 'notFound') {
    statusBar.backgroundColor = new vscode.ThemeColor('statusBarItem.warningBackground');
    statusBar.color = new vscode.ThemeColor('statusBarItem.warningForeground');
  } else {
    statusBar.backgroundColor = undefined;
    statusBar.color = undefined;
  }
}

function activate(context) {
  outputChannel = vscode.window.createOutputChannel('Dotfiles Check');
  statusBar = vscode.window.createStatusBarItem(vscode.StatusBarAlignment.Left, 100);
  statusBar.command = 'dotfiles-check.verify';
  statusBar.show();

  const verifyCmd = vscode.commands.registerCommand('dotfiles-check.verify', async () => {
    const workspaceFolder = vscode.workspace.workspaceFolders?.[0];
    const projectDir = workspaceFolder?.uri.fsPath;

    if (!projectDir) {
      log('No workspace open — skipping');
      updateStatusBar('No workspace', 'skipped');
      statusBar.hide();
      return;
    }

    // Gate: only act on git repos owned by an allowed owner, and only at the
    // repo root. This prevents creating CLAUDE.md symlinks in arbitrary folders
    // (e.g. random scratch dirs or third-party repos).
    const repoInfo = await inspectGitRepo(projectDir);

    if (!repoInfo.isRepo) {
      log(`Skipping ${projectDir}: not a git repository`);
      updateStatusBar('Not a git repo', 'skipped');
      statusBar.hide();
      return;
    }

    if (!repoInfo.isRoot) {
      log(`Skipping ${projectDir}: not the git root`);
      updateStatusBar('Not git root', 'skipped');
      statusBar.hide();
      return;
    }

    const allowedOwners = getAllowedOwners();
    if (!repoInfo.owner || !allowedOwners.includes(repoInfo.owner)) {
      log(`Skipping ${projectDir}: remote '${repoInfo.remoteUrl || '<none>'}' is not from an allowed owner (${allowedOwners.join(', ')})`);
      updateStatusBar('External repo — skipped', 'skipped');
      statusBar.hide();
      return;
    }

    if (!repoInfo.hasCommits) {
      log(`Skipping ${projectDir}: repo has no commits yet (fresh git init)`);
      updateStatusBar('Empty repo — skipped', 'skipped');
      statusBar.hide();
      return;
    }

    // From here on we know it's one of the user's own repos at its root.
    statusBar.show();

    const dotfilesPath = await getDotfilesPath();
    if (!dotfilesPath || !fs.existsSync(dotfilesPath)) {
      const action = await vscode.window.showWarningMessage(
        'Dotfiles not found',
        { modal: true, detail: `Expected at: ${dotfilesPath}\n\nRun setup to initialize dotfiles.` },
        'Setup',
        'Skip'
      );
      if (action === 'Setup') {
        const terminal = vscode.window.createTerminal('Setup Dotfiles');
        const parentDir = dotfilesPath ? path.dirname(dotfilesPath) : '~';
        terminal.sendText(`cd "${parentDir}" && git clone https://github.com/nic2045/dotfiles.git && cd dotfiles && bash setup.sh`);
        terminal.show();
      }
      return;
    }

    const claudeCheck = checkClaudeMd(projectDir, dotfilesPath);
    if (!claudeCheck.ok) {
      const projectName = path.basename(projectDir);
      log(`CLAUDE.md issue: ${claudeCheck.issue} — auto-fixing`);
      updateStatusBar('Setting up CLAUDE.md...', 'syncing');
      try {
        const targetDir = path.dirname(claudeCheck.expectedTarget);
        if (!fs.existsSync(targetDir)) fs.mkdirSync(targetDir, { recursive: true });
        const targetCreated = !fs.existsSync(claudeCheck.expectedTarget);
        if (targetCreated) {
          fs.writeFileSync(
            claudeCheck.expectedTarget,
            `# ${projectName} — Claude Instructions\n\n@../CLAUDE.md\n\n<!-- Add project-specific instructions here -->\n`
          );
        }
        try { fs.unlinkSync(claudeCheck.claudeMdPath); } catch {}
        fs.symlinkSync(`../dotfiles/claude/projects/${projectName}.md`, claudeCheck.claudeMdPath);
        log(`CLAUDE.md symlink created for ${projectName}`);

        await protectProjectRepo(projectDir);

        if (targetCreated) {
          await pushProjectToDotfiles(dotfilesPath, projectName, claudeCheck.expectedTarget);
        }

        updateStatusBar('Up to date', 'synced');
        // Non-blocking toast, auto-dismisses. No buttons, no decisions.
        // Claude Code reads CLAUDE.md on session start — next time it starts
        // (next window/session) the new file is picked up automatically.
        vscode.window.setStatusBarMessage(
          `$(check) CLAUDE.md set up for ${projectName}`,
          5000
        );
      } catch (err) {
        log(`Auto-fix failed: ${err.message}`);
        updateStatusBar('Auto-fix failed', 'error');
        vscode.window.showErrorMessage(`Dotfiles auto-fix failed: ${err.message}`);
      }
      return;
    }

    log('Dotfiles verified');
    updateStatusBar('Up to date', 'synced');
  });

  const syncCmd = vscode.commands.registerCommand('dotfiles-check.sync', syncDotfiles);

  context.subscriptions.push(verifyCmd, syncCmd, statusBar, outputChannel);

  // Initial verify on startup
  vscode.commands.executeCommand('dotfiles-check.verify');

  // Background sync every 6 hours
  syncInterval = setInterval(syncDotfiles, 6 * 60 * 60 * 1000);
  log('Extension activated — background sync every 6 hours');
}

function deactivate() {
  if (syncInterval) clearInterval(syncInterval);
}

module.exports = { activate, deactivate };
